### ISSUE TITLE
Space Travelers Hub

### ISSUE THREAD

**Issue by Jeddaa** [kimitaWanjohi/space-travelers-hub#49]
Project link: https://github.com/kimitaWanjohi/space-travelers-hub/projects/1
There are two people in this team for the space travellers hub project.

**Comment by Olamarx** [comment]
> Project link: https://github.com/kimitaWanjohi/space-travelers-hub/projects/1 There are two people in this team for the space travellers hub project.

Hi Team, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Fair distribution ✔️
- Kanban board usage ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I can see some tasks are not assigned at all, I would implore you to assign them too since they are part of a project of the tasks to be executed.
![image](https://github.com/kimitaWanjohi/space-travelers-hub/assets/86200356/2d65fcba-7c2e-49d0-9c62-ca420153d398)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BregornOriginal** [comment]
Hi @Jeddaa and @kimitaWanjohi 

Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! 

![giphy](https://github.com/kimitaWanjohi/space-travelers-hub/assets/93630700/9314a5e2-fa84-4052-9428-49c3f233fae0)

## Highlights

✔️ Excellent work setup the Kanban board

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)
